import http from 'k6/http';
import { check } from 'k6';

const movies = [
    'Flubber',
    'Patch Adams',
    'The Avengers',
    "Enter the Fist",
    "Double Dragon",
    "flubber",
    "Jurassic Park",
    "ET",
    "E.T.",
    "The departed",
    "Her",
    "Servant",
    "black-ish",
    "Bird Box",
    "Star Wars",
    "hitch",
    "serendipity",
    "speed",
    "one",
    "happy gilmore",
    "eight crazy nights",
    "wedding singer",
    "click",
    "Sky high",
    "Parasite",
    "Toy story",
    "Independence Day",
    "Gremlins",
    "Marriage Story",
    "Gremlins 2",
    "Chicken Run",
    "Antz",
    "A Bug's Life",
    "Carrie",
    "Aliens",
    "Looper",
    "21",
    "Chronicles of riddick",
    "Ant man",
    "the mask",
    "the number 23",
    "John Wick",
    "The lake house",
    "Point Break",
    "Lake House",
    "Bill and ted",
    "The matrix",
    "Knock knock",
    "Valentine’s Day",
    "Valentine's day",
    "Leap Year",
    "The holiday",
    "Just friends",
    "shallow hal",
    "Made of honor",
    "maid of honor",
    "Maid in manhattan",
    "Catwoman",
    "Monster's Ball",
    "Scream",
    "Zaat",
    "Cabin in the woods",
    "Spookies",
    "Ouija",
    "Friday the 13th",
    "Silent night, deadly night 2",
    "Hack o lantern",
    "Silent night deadly night",
    "Silent Night, Deadly Night part 2",
    "Miss congeniality",
    "The blind side",
    "Speed 2",
    "The proposal",
    "Oceans 8",
    "Ocean’s 8",
    "miss congeniality 2",
    "My big fat Greek wedding",
    "Bride wars",
    "My best friend’s wedding",
    "Four weddings and a funeral",
    "I now pronounce you",
    "Ready or not",
    "I Now Pronounce You Chuck & Larry",
    "madea",
    "the wedding singer",
    "wedding crashers",
    "Swordfish",
    "X-men",
    "X2",
    "Die another day",
    "Boomerang",
    "Cloud atlas",
    "Robots",
    "New year's Eve",
    "The Last Crusade",
    "Halloween",
    "The Room",
    "The Prestige",
    "All about steve",
    "Twelve Monkeys",
    "The Hamster Factor and Other Tales of Twelve Monkeys",
]

const getMovie = () => movies[Math.floor(Math.random() * movies.length)];

const url = 'https://perfect-movie-game.now.sh/api/score/';

export default function () {
    let res = http.get(`${url}${getMovie()}`);
    check(res, {
        'is status 200': (r) => r.status === 200,
    });
}
